### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by Riccardocode** [Riccardocode/lastCall#4]
When In smaller screen the width of the login button is not proportioned
![Screenshot 2023-12-09 073319](https://github.com/Riccardocode/lastCall/assets/52591461/b7d4aa81-4664-4fbb-bf14-1627214b0642)

**Comment by antomart96** [comment]
ok nice thank you, it will be done !

**Comment by la-viza** [comment]
Thanks, @Riccardocode. I'm working on it right now.

**Comment by Riccardocode** [comment]
well done
